substitutions:
  _RUN: dg03
  _LINK: https://drive.google.com/uc?id=1mTINbkOpqW2dXl9bgGt_zwR365BKhHyn
  _SERVICE_NAME: inference
  _LABELS: gcb-trigger-id=f4672807-a838-4990-a59c-bf8e18c1ef17
  _TRIGGER_ID: f4672807-a838-4990-a59c-bf8e18c1ef17
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
options:
  substitutionOption: ALLOW_LOOSE
steps:
- name: 'python:3.8-slim'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    cd "AI/Cloud Run"
    pip3 install gdown \
    && gdown "$_LINK" \
    && tar -xf ./checkpoint_$_RUN.tar
  id: Download Model
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '--no-cache'
    - '-t'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    - "AI/Cloud Run"
    - '-f'
    - "AI/Cloud Run/Dockerfile"
    - '--build-arg'
    - 'ARGRUN=$_RUN'
  id: Build
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
    - run
    - services
    - update
    - $_SERVICE_NAME
    - '--platform=managed'
    - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    - >-
      --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
    - '--region=$_DEPLOY_REGION'
    - '--quiet'
  id: Deploy
  entrypoint: gcloud
timeout: 1020s

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - inference