pipeline {
  agent any
  stages {
    stage('Deploy') {
      steps {
        sh '''cd /word-counter-bot-dev && 
sudo git pull && 
sudo screen -d -m .github/workflows/execution.sh'''
      }
    }

  }
}