on: [push]

name: DeployAI

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Invoke Cloud Build and Jenkins Build on Git Diff
        run: ./.github/workflows/invoke.sh "${{secrets.WEBHOOKURL}}" "${{secrets.JENKINSURL}}"