on: [push]

name: DeployAI

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Invoke Cloud Build on Git Diff
        run: ./.github/workflows/invoke.sh ${{secrets.WEBHOOKURL}}